/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import util.Koneksi;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import controller.ControllerBarang;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import model.ModelBarang;
import util.Koneksi;
/**
 *
 * @author Rizki Pratama
 */
public class ViewBarang extends javax.swing.JFrame {

    Koneksi koneksi = new Koneksi();
    ControllerBarang cb = new ControllerBarang();
    ModelBarang mb = new ModelBarang();
    /**
     * Creates new form ViewBarang
     */
    public ViewBarang() {
        initComponents();
        dataTable();
        CenterForm();
    }

    private void CenterForm() {
        Dimension ScreenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
        (ScreenSize.width - frameSize.width)/2,
        (ScreenSize.height - frameSize.height)/2);
    }
    
    private void baru() {
        jButtonBaru.setEnabled(false);
        jButtonSimpan.setEnabled(true);
        jButtonUbah.setEnabled(false);
        jButtonHapus.setEnabled(false);
        jTextFieldNama.setEditable(true);
        jTextFieldJenis.setEditable(true);
        jTextFieldJumlah.setEditable(true);
        bersih();
    }
    
    private void bersih2(){
        jButtonBaru.setEnabled(true);
        jButtonSimpan.setEnabled(false);
        jButtonUbah.setEnabled(false);
        jButtonHapus.setEnabled(false);
        jTextFieldNama.setEditable(false);
        jTextFieldJenis.setEditable(false);
        jTextFieldJumlah.setEditable(false);
        bersih();
    }
    
    private void bersih(){
        jTextFieldId.setText("");
        jTextFieldNama.setText("");
        jTextFieldJenis.setText("");
        jTextFieldJumlah.setText("");
        jTextFieldNama.requestFocus();
    }
    
    private void ubahDanHapus(){
        jButtonSimpan.setEnabled(false);
        jTextFieldNama.setEditable(true);
        jTextFieldJenis.setEditable(true);
        jTextFieldJumlah.setEditable(true);
        jButtonUbah.setEnabled(true);
        jButtonHapus.setEnabled(true);
    }
    
    private void dataTable(){
        koneksi.koneksidatabase();
        
        DefaultTableModel tabel = new DefaultTableModel();
        
        tabel.addColumn("ID");
        tabel.addColumn("Nama");
        tabel.addColumn("Jenis");
        tabel.addColumn("Jumlah");
        
        jTableBarang.setModel(tabel);
        try {
            String sql = "select * from tbl_barang";
            
            ResultSet res = koneksi.state.executeQuery(sql);
            while (res.next()) {
                tabel.addRow(new Object[]{
                    res.getString("id"),
                    res.getString("nama"),
                    res.getString("jenis"),
                    res.getString("jumlah")
                });
                jTableBarang.setModel(tabel);
            }
        } catch (Exception eer) {
            System.err.println("SQLException:" + eer.getMessage());
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldJumlah = new javax.swing.JTextField();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldNama = new javax.swing.JTextField();
        jTextFieldJenis = new javax.swing.JTextField();
        jButtonTutup = new javax.swing.JButton();
        jButtonBaru = new javax.swing.JButton();
        jButtonSimpan = new javax.swing.JButton();
        jButtonBersih = new javax.swing.JButton();
        jButtonUbah = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableBarang = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("id Barang :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setText("Nama Barang :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel4.setText("Jenis Barang :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel5.setText("Jumlah Barang :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        getContentPane().add(jTextFieldJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 140, -1));

        jTextFieldId.setEnabled(false);
        getContentPane().add(jTextFieldId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 140, -1));
        getContentPane().add(jTextFieldNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 140, -1));
        getContentPane().add(jTextFieldJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 140, -1));

        jButtonTutup.setText("Tutup");
        jButtonTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTutupActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTutup, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 80, -1));

        jButtonBaru.setText("Baru");
        jButtonBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBaruActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 80, -1));

        jButtonSimpan.setText("Simpan");
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 80, -1));

        jButtonBersih.setText("Bersih");
        jButtonBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBersihActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 80, -1));

        jButtonUbah.setText("Ubah");
        jButtonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUbahActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 80, -1));

        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 80, -1));

        jTableBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBarangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableBarang);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 640, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        // TODO add your handling code here:
        try {
            String nama = jTextFieldNama.getText();
            String jenis = jTextFieldJenis.getText();
            int jumlah = Integer.parseInt(jTextFieldJumlah.getText());
            
            mb.setNama(nama);
            mb.setJenis(jenis);
            mb.setJumlah(jumlah);
            cb.simpanData(mb);
            dataTable();
            bersih2();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Harap Masukan ANgka");
            jTextFieldNama.setText("");
            jTextFieldNama.requestFocus();
        }
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jButtonBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBaruActionPerformed
        // TODO add your handling code here:
        baru();
    }//GEN-LAST:event_jButtonBaruActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(jTextFieldId.getText());
            
            mb.setId(id);
            cb.hapusData(mb);
            
            dataTable();
            bersih2();
            bersih();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Harap Masukan Nama");
        }
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jButtonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUbahActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(jTextFieldId.getText());
            String nama = jTextFieldNama.getText();
            String jenis = jTextFieldJenis.getText();
            int jumlah = Integer.parseInt(jTextFieldJumlah.getText());
            
            mb.setId(id);
            mb.setNama(nama);
            mb.setJenis(jenis);
            mb.setJumlah(jumlah);
            cb.ubahData(mb);
            
            bersih2();
            dataTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Harap Masukan Nama");
        }
    }//GEN-LAST:event_jButtonUbahActionPerformed

    private void jTableBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBarangMouseClicked
        // TODO add your handling code here:
        ubahDanHapus();
        try {
            int baris = jTableBarang.getSelectedRow();
            jTextFieldId.setText(jTableBarang.getValueAt(baris, 0).toString());
            jTextFieldNama.setText(jTableBarang.getValueAt(baris, 1).toString());
            jTextFieldJenis.setText(jTableBarang.getValueAt(baris, 2).toString());
            jTextFieldJumlah.setText(jTableBarang.getValueAt(baris, 3).toString());
        } catch (Exception e) {
            System.err.println("Error : " + e);
        }
    }//GEN-LAST:event_jTableBarangMouseClicked

    private void jButtonBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBersihActionPerformed
        // TODO add your handling code here:
        bersih();
    }//GEN-LAST:event_jButtonBersihActionPerformed

    private void jButtonTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTutupActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonTutupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBaru;
    private javax.swing.JButton jButtonBersih;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JButton jButtonTutup;
    private javax.swing.JButton jButtonUbah;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableBarang;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldJenis;
    private javax.swing.JTextField jTextFieldJumlah;
    private javax.swing.JTextField jTextFieldNama;
    // End of variables declaration//GEN-END:variables
}
